#!/usr/bin/env bash
# This script is displaying "the hours and mins""
hou=0
min=1

while ((hou <= 12)); do 
	while ((min <= 59)); do
		echo $min
		min=$((min+1))
		done
	echo $hou
	hou=$((hou+1))
done