#!/usr/bin/env bash
# This script is displaying "the hours and mins?""
hou=0
min=1

while ((hou <= 12)); do 
	echo "Hour: $hou"
	while ((min <= 59)); do
		echo $min
		min=$((min+1))
		done
	hou=$((hou+1))
	min=1
done
